export const AUTH_USER = 'AUTH_USER'
export const SET_ROLE = 'SET_ROLE'

export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'

export const LOGIN_ERROR = 'LOGIN_ERROR'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const GET_DOCTORS = 'GET_DOCTORS'
export const SET_DOCTORS = 'SET_DOCTORS'

export const ADD_DOCTOR = 'ADD_DOCTOR'
export const SET_DOCTOR = 'SET_DOCTOR'

export const DELETE_DOCTOR = 'DELETE_DOCTOR'

export const GET_CLINICAL_CENTERS = 'GET_CLINICAL_CENTERS'
export const SET_CLINICAL_CENTERS = 'SET_CLINICAL_CENTERS'

export const GET_CLINICAL_CENTER = 'GET_CLINICAL_CENTER'

