export const AUTH_USER = 'AUTH_USER'
export const SET_ROLE = 'SET_ROLE'
export const SET_USER_EMAIL = 'SET_USER_EMAIL'

export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const LOGOUT = 'LOGOUT'

export const LOGIN_ERROR = 'LOGIN_ERROR'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const GET_DOCTORS = 'GET_DOCTORS'
export const SET_DOCTORS = 'SET_DOCTORS'

export const ADD_DOCTOR = 'ADD_DOCTOR'
export const SET_DOCTOR = 'SET_DOCTOR'

export const DELETE_DOCTOR = 'DELETE_DOCTOR'

export const GET_CLINICS = 'GET_CLINICS'
export const SET_CLINICS = 'SET_CLINICS'

export const GET_CLINICAL_CENTER = 'GET_CLINICAL_CENTER'

export const GET_APPOINTMENT_TYPES = "GET_APPOINTMENT_TYPES";
export const SET_APPOINTMENT_TYPES = "SET_APPOINTMENT_TYPES"

export const SET_APPOINTMENT_TERMS = "SET_APPOINTMENT_TERMS"

export const GET_APPOINTMENT_CHECK = "GET_APPOINTMENT_CHECK"
export const SET_APPOINTMENT_CHECK = "SET_APPOINTMENT_CHECK"

export const POST_APPOINTMENT = "POST_APPOINTMENT";
export const GET_APPOINTMENT = "GET_APPOINTMENT";
export const PUT_APPOINTMENT = "PUT_APPOINTMENT";

export const GET_HALLS = 'GET_HALLS'
export const SET_HALLS = 'SET_HALLS'
export const SEARCH_HALLS = 'SEARCH_HALLS'
