export const AUTH_USER = 'AUTH_USER'
export const SET_ROLE = 'SET_ROLE'
export const SET_USER_EMAIL = 'SET_USER_EMAIL'

export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const LOGOUT = 'LOGOUT'
export const CHANGEPASS = 'CHANGEPASS'
export const SET_CHANGEDPASS = 'SET_CHANGEDPASS'
export const GET_PROFILE = 'GET_PROFILE'
export const SET_PROFILE = 'SET_PROFILE'
export const EDIT_PROFILE = 'EDIT_PROFILE'

export const LOGIN_ERROR = 'LOGIN_ERROR'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const DELETE_ERROR = 'DELETE_ERROR'
export const ADD_ERROR = 'ADD_ERROR'
export const EDIT_ERROR = 'EDIT_ERROR'
export const RESET_ERROR = 'RESET_ERROR'

export const GET_DOCTORS = 'GET_DOCTORS'
export const SET_DOCTORS = 'SET_DOCTORS'

export const ADD_DOCTOR = 'ADD_DOCTOR'
export const SET_DOCTOR = 'SET_DOCTOR'
export const DELETE_DOCTOR = 'DELETE_DOCTOR'
export const SET_DELETED_DOCTOR = 'SET_DELETED_DOCTOR'

export const GET_CLINICS = 'GET_CLINICS'
export const SET_CLINICS = 'SET_CLINICS'
export const SET_AVAILABLE_CLINICS = 'SET_AVAILABLE_CLINICS'

export const GET_CLINICAL_CENTER = 'GET_CLINICAL_CENTER'

export const GET_APPOINTMENT_TYPES = "GET_APPOINTMENT_TYPES";
export const SET_APPOINTMENT_TYPES = "SET_APPOINTMENT_TYPES"

export const SET_APPOINTMENT_TERMS = "SET_APPOINTMENT_TERMS"

export const GET_APPOINTMENT_CHECK = "GET_APPOINTMENT_CHECK"
export const SET_APPOINTMENT_CHECK = "SET_APPOINTMENT_CHECK"

export const POST_APPOINTMENT = "POST_APPOINTMENT";
export const GET_APPOINTMENT = "GET_APPOINTMENT";
export const PUT_APPOINTMENT = "PUT_APPOINTMENT";
export const SCHEDULE_APPOINTMENT = "SCHEDULE_APPOINTMENT";

export const GET_HALLS = 'GET_HALLS'
export const SET_HALLS = 'SET_HALLS'
export const SEARCH_HALLS = 'SEARCH_HALLS'
export const ADD_HALL = 'ADD_HALL'
export const SET_HALL = 'SET_HALL'
export const DELETE_HALL = 'DELETE_HALL'
export const SET_DELETED_HALL = 'SET_DELETED_HALL'
export const EDIT_HALL = 'EDIT_HALL'
export const SET_EDITED_HALL = 'SET_EDITED_HALL'

export const GET_PATIENTS = 'GET_PATIENTS'
export const SET_PATIENTS = 'SET_PATIENTS'
export const GET_PATIENT = 'GET_PATIENT'
export const SET_PATIENT = 'SET_PATIENT'
export const PUT_PATIENT = 'PUT_PATIENT'
export const SEARCH_PATIENTS = 'SEARCH_PATIENTS'

export const GET_TYPES = 'GET_TYPES'
export const SET_TYPES = 'SET_TYPES'
export const SEARCH_TYPES = 'SEARCH_TYPES'
export const ADD_TYPE = 'ADD_TYPE'
export const SET_TYPE = 'SET_TYPE'
export const DELETE_TYPE = 'DELETE_TYPE'
export const SET_DELETED_TYPE = 'SET_DELETED_TYPE'
export const EDIT_TYPE = 'EDIT_TYPE'
export const SET_EDITED_TYPE = 'SET_EDITED_TYPE'

export const GET_REQUESTS = 'GET_REQUESTS'
export const SET_REQUESTS = 'SET_REQUESTS'
export const RESOLVE_REQUEST = 'RESOLVE_REQUEST'
export const REMOVE_REQUEST = 'REMOVE_REQUEST'
