# Generated by Django 3.0.5 on 2020-05-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='typeOf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.AppointmentType'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='appointmentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='clinics.AppointmentType'),
        ),
    ]
