# Generated by Django 3.0.5 on 2020-05-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_auto_20200502_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttype',
            name='typeName',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='appointmentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='clinics.AppointmentType', unique=True),
        ),
    ]
