# Generated by Django 3.0.5 on 2020-05-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200429_1601'),
        ('clinics', '0004_auto_20200502_2301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('clinic', 'dateTime', 'doctor')},
        ),
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together={('clinic', 'appointmentType')},
        ),
    ]
