# Generated by Django 3.0.5 on 2020-05-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_auto_20200502_2306'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('clinic', 'dateTime', 'doctor'), name='unique doctor date time for a clinic'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('clinic', 'appointmentType'), name='unique appointment type price for clinic'),
        ),
    ]
