# Generated by Django 3.0.5 on 2020-05-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='typeOf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='clinics.AppointmentType'),
        ),
    ]
