# Generated by Django 3.0.5 on 2020-05-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_auto_20200504_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='typeOf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.AppointmentType'),
        ),
        migrations.AddConstraint(
            model_name='clinicrating',
            constraint=models.UniqueConstraint(fields=('clinic', 'patient'), name='one clinic rating per patient'),
        ),
        migrations.AddConstraint(
            model_name='doctorrating',
            constraint=models.UniqueConstraint(fields=('doctor', 'patient'), name='one doctor rating per patient'),
        ),
    ]
