# Generated by Django 3.0.5 on 2020-05-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_auto_20200504_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='operatingRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.OperatingRoom'),
        ),
    ]
