# Generated by Django 3.0.3 on 2020-05-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_auto_20200508_1701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operatingroom',
            unique_together={('clinic', 'name')},
        ),
    ]
