# Generated by Django 3.0.3 on 2020-05-13 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_auto_20200513_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='operatingRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.OperatingRoom'),
        ),
    ]
