# Generated by Django 3.0.5 on 2020-06-14 16:37

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0029_auto_20200609_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['typeOf', 'date']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
    ]
