# Generated by Django 3.0.3 on 2020-04-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200411_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=70, primary_key=True, serialize=False, unique=True),
        ),
    ]
