# Generated by Django 3.0.3 on 2020-04-21 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_clinicadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicadmin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminAccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
