# Generated by Django 3.0.3 on 2020-05-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200503_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='employee',
        ),
        migrations.AddField(
            model_name='doctor',
            name='schedule',
            field=models.ManyToManyField(to='users.Schedule'),
        ),
    ]
