# Generated by Django 3.0.3 on 2020-05-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('users', '0013_auto_20200503_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicadmin',
            name='employedAt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='clinics.Clinic'),
        ),
    ]
