# Generated by Django 3.0.3 on 2020-05-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_clinicadmin_employedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='schedule',
            field=models.ManyToManyField(null=True, to='users.Schedule'),
        ),
    ]
