# Generated by Django 3.0.3 on 2020-05-03 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200503_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='users.Doctor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('day', 'startTime', 'endTime')},
        ),
    ]
