# Generated by Django 3.0.3 on 2020-05-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200504_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='employee',
        ),
    ]
