# Generated by Django 3.0.3 on 2020-05-03 22:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_schedule_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='users.Doctor'),
            preserve_default=False,
        ),
    ]
