# Generated by Django 3.0.3 on 2020-05-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_schedule_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Firday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
