# Generated by Django 3.0.3 on 2020-05-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200506_1415'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('day', 'employee')},
        ),
    ]
