# Generated by Django 3.0.5 on 2020-05-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200506_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='activated',
        ),
        migrations.AddField(
            model_name='patient',
            name='activation_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
